# Practice-Session 2

## What is the Season_id of the African Cup of Nations?

In [12]:
import os
from statsbombpy import sb
import warnings
warnings.filterwarnings("ignore", message="credentials were not supplied")

In [13]:
df_competitions = sb.competitions()

In [14]:
df_competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [15]:
df_African_Cup = df_competitions[ df_competitions.competition_name == "African Cup of Nations" ]
df_African_Cup

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538

In [16]:
df_matches = sb.matches(
    competition_id=1267,
    season_id=107,
)

In [17]:
df_matches.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3923881,2024-02-11,22:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Côte d'Ivoire,1,2,available,...,None,8,Final,Stade Olympique Alassane Ouattara,Dahane Beida,José Vítor dos Santos Peseiro,Emerse Faé,1.1.0,2,2
1,3923880,2024-02-10,22:00:00.000,Africa - African Cup of Nations,2023,South Africa,Congo DR,0,0,available,...,None,7,3rd Place Final,Stade Félix Houphouët-Boigny,Bamlak Tessema Weyesa,Hugo Henri Broos,Sébastien Desabre,1.1.0,2,2
2,3922838,2024-02-07,22:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Congo DR,1,0,available,...,None,6,Semi-finals,Stade Olympique Alassane Ouattara,Ibrahim Mutaz,Emerse Faé,Sébastien Desabre,1.1.0,2,2
3,3922837,2024-02-07,19:00:00.000,Africa - African Cup of Nations,2023,Nigeria,South Africa,1,1,available,...,None,6,Semi-finals,Stade de Bouaké,Amin Mohamed Omar,José Vítor dos Santos Peseiro,Hugo Henri Broos,1.1.0,2,2
4,3922242,2024-01-29,22:00:00.000,Africa - African Cup of Nations,2023,Senegal,Côte d'Ivoire,1,1,available,...,None,4,Round of 16,Stade Charles Konan Banny de Yamoussoukro,Pierre Ghislain Atcho,Aliou Cissé,Emerse Faé,1.1.0,2,2

## Name three players who played in the final match of the African Cup of Nations.

In [18]:
df_events = sb.events(match_id=3923881)

In [19]:
print(df_events['player'].dropna())

6                           Ademola Lookman
7                      William Troost-Ekong
8                   Calvin Bassey Ughelumba
9       Oluwasemilogo Adesewo Ibidapo Ajayi
10                             Yahia Fofana
                       ...
2690                           Frank Onyeka
2691                           Zaidu Sanusi
2692                       Sébastien Haller
2693                            Seko Fofana
2694                      Jean Michaël Seri
Name: player, Length: 2676, dtype: object